version: 0.0
os: linux

files:
  - source: app/app.jar
    destination: /home/ec2-user/app
  - source: scripts/
    destination: /home/ec2-user/scripts
  - source: systemd/
    destination: /home/ec2-user/systemd

permissions:
  - object: /home/ec2-user/scripts
    pattern: "*"
    owner: ec2-user
    group: ec2-user
    mode: 755
  - object: /home/ec2-user/app
    pattern: "*"
    owner: ec2-user
    group: ec2-user
    mode: 644

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 600
      runas: ec2-user
  ApplicationStop:
    - location: scripts/stop_app.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 600
      runas: ec2-user
  ValidateService:
    - location: scripts/validate.sh
      timeout: 600
      runas: ec2-user
